export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';

export const GET_ARTICLE_DETAILED_REQUEST = 'GET_ARTICLE_DETAILED_REQUEST';
export const GET_ARTICLE_DETAILED_SUCCESS = 'GET_ARTICLE_DETAILED_SUCCESS';
export const GET_ARTICLE_DETAILED_FAILURE = 'GET_ARTICLE_DETAILED_FAILURE';

export const POST_NEW_ARTICLE = 'POST_NEW_ARTICLE';
export const POST_NEW_ARTICLE_SUCCESS = 'POST_NEW_ARTICLE_SUCCESS';
export const POST_NEW_ARTICLE_FAILURE = 'POST_NEW_ARTICLE_FAILURE';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';

export const PUT_EDIT_ARTICLE = 'PUT_EDIT_ARTICLE';
export const PUT_EDIT_ARTICLE_SUCCESS = 'PUT_EDIT_ARTICLE_SUCCESS';
export const PUT_EDIT_ARTICLE_FAILURE = 'PUT_EDIT_ARTICLE__FAILURE';

export const POST_FAVORITE = 'POST_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const POST_REGISTRATION = 'POST_REGISTRATION';
export const POST_REGISTRATION_SUCCESS = 'POST_REGISTRATION_SUCCESS';
export const POST_REGISTRATION_FAILURE = 'POST_REGISTRATION_FAILURE';

export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';

export const PUT_EDIT_PROFILE = 'PUT_EDIT_PROFILE';
export const PUT_EDIT_PROFILE_SUCCESS = 'PUT_EDIT_PROFILE_SUCCESS';
export const PUT_EDIT_PROFILE_FAILURE = 'PUT_EDIT_PROFILE_FAILURE';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const LOG_OUT = 'LOG_OUT';

export const CLEAR_ARTICLE = 'CLEAR_ARTICLE';
